# Generated by Django 4.1.2 on 2022-10-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal",
            name="is_staffed",
            field=models.CharField(
                choices=[("True", True), ("False", False)], default=False, max_length=10
            ),
        ),
    ]
